

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=host.docker.internal:9092
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - hotel-service-1
      - hotel-service-2
      - hotel-service-3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  hotel-service-1:
    build: .
    container_name: hotel-service-1
    ports:
      - "8080:8081"
    networks:
      - app-network
    depends_on:
      - cache
  hotel-service-2:
    build: .
    container_name: hotel-service-2
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - cache
  hotel-service-3:
    build: .
    container_name: hotel-service-3
    ports:
      - "8082:8081"
    networks:
      - app-network
    depends_on:
      - cache
  cache:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
volumes:
    redis_data:
      driver: local
networks:
  app-network:
    driver: bridge